apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsstorage
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.180.0.71
    path: "/mnt/user/kubernetes/portainer"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfsstorage
spec:
  storageClassName: storage-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
